# Generated by Django 5.1.7 on 2025-04-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_abe_policy_patient_ibe_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ibe_policy',
        ),
    ]
