# Generated by Django 5.1.2 on 2025-04-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_labtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='abe_policy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
